version: '2'

networks:
  default:
    external:
      name: ${DC_NETWORK}

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/${ES_VERSION}
    container_name: ${DC_PREFIX}-elasticsearch
    environment:
      - cluster.name=matchid-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # mem_limit: 1024mM
    volumes:
      - ./esdata/node1:/usr/share/elasticsearch/data
    # ports:
    #   - 9200:9200


